version: '3.8'

services:
  # Service Golang (Downloader & Orchestrator)
  go-app:
    build: .
    container_name: mvp-clipper-go
    ports:
      - "8080:8080"
    volumes:
      # Mapping folder host "./temp_videos" ke dalam container di "/app/shared"
      - ./temp_videos:/app/shared
      # Keep local tmp just in case, or for logs
      - ./tmp:/app/tmp
    environment:
      - VIDEO_STORAGE_PATH=/app/shared
      - PYTHON_SERVICE_URL=http://python-app:5000
    depends_on:
      - python-app
    restart: unless-stopped
    networks:
      - clipper-network

  # Service Python (Face Recognition Worker)
  python-app:
    build: ./python-app
    container_name: mvp-clipper-python
    ports:
      - "5000:5000"
    volumes:
      # PENTING: Mapping ke folder yang SAMA di dalam container
      - ./temp_videos:/app/shared
    environment:
      - VIDEO_STORAGE_PATH=/app/shared
    restart: unless-stopped
    networks:
      - clipper-network

networks:
  clipper-network:
    driver: bridge
